### ISSUE TITLE
Improve docker-compose for using latest template

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-couchdb#1]

**Comment by qiaofeng1227** [comment]
Notice:
1.  support Multiple versions
2.  compose file refer to: https://registry.hub.docker.com/_/couchdb

**Comment by qiaofeng1227** [comment]
confirm container‘s /opt/couchdb/etc/local.d files

**Comment by viafcccy** [comment]
1.docker run
![image](https://user-images.githubusercontent.com/45913187/115188543-a638eb80-a117-11eb-9048-2312bcf71da7.png)
2.docker compose
![image](https://user-images.githubusercontent.com/45913187/115188746-f31cc200-a117-11eb-8658-ffe802672a31.png)
![image](https://user-images.githubusercontent.com/45913187/115189639-5c510500-a119-11eb-878d-67589abc9c10.png)
conclusion:
1. docker.ini was created in container after container booted, it will be synchronized with the host when container running.
2. just docker.ini file is useful.
